name: 'Minimal Test'
description: 'Test for ytdlmusic'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - name: "minimal use case"
      shell: bash
      run: |          
        printf '3\n' | ytdlmusic "Rexlambo Stay With Me"
        test -f "Rexlambo Stay With Me.m4a"
        file -b "Rexlambo Stay With Me.m4a" | grep "ISO Media, MPEG v4 system, Dynamic Adaptive Streaming over HTTP"   