name: 'Minimal Test'
description: 'Test for ytdlmusic'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - name: "minimal use case"
      shell: bash
      run: |          
        printf '3\n' | ytdlmusic "Rexlambo" "Stay With Me"
        test -f rexlambo_stay_with_me.m4a
        file -b rexlambo_stay_with_me.m4a | grep "ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]"   