name: 'Full Test'
description: 'Full Test for ytdlmusic'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - name: test 'ytdlmusic'   
      shell: bash      
      run: |
        echo "---->ytdlmusic"
        ytdlmusic
        echo "---->test the return content"
        ytdlmusic | grep "usage: "                
    - name: test 'ytdlmusic --version'
      shell: bash 
      run: |
        echo "---->ytdlmusic --version"
        ytdlmusic --version
        echo "---->test the return content"
        ytdlmusic --version | grep "ytdlmusic version             :" 
    - name: test mp3
      shell: bash
      run: | 
        echo '---->ytdlmusic --auto "Rexlambo Stay With Me"'         
        ytdlmusic --auto "Rexlambo Stay With Me"
        echo "---->test if file exists"
        test -f "Rexlambo Stay With Me.mp3"
        echo "---->test the file type"
        file -b "Rexlambo Stay With Me.mp3" | grep "Audio file with ID3 version 2.4.0, contains:MPEG ADTS, layer III, v1, 256 kbps, 48 kHz, Stereo"
    - name: test m4a
      shell: bash
      run: |
        echo '---->ytdlmusic -f --auto "Rexlambo Stay With Me"'  
        ytdlmusic -f --auto "Rexlambo Stay With Me"
        echo "---->test if file exists"
        test -f "Rexlambo Stay With Me_1.m4a"
        echo "---->test the file type"
        file -b "Rexlambo Stay With Me_1.m4a" | grep "ISO Media, MPEG v4 system, Dynamic Adaptive Streaming over HTTP"
    - name: test ogg
      shell: bash
      run: | 
        echo '---->ytdlmusic -yo "Rexlambo Stay With Me"' 
        ytdlmusic -yo "Rexlambo Stay With Me"
        echo "---->test if file exists"
        test -f "Rexlambo Stay With Me.ogg"
        echo "---->test the file type"
        file -b "Rexlambo Stay With Me.ogg" | grep -b "Ogg data, Vorbis audio, stereo, 48000 Hz, ~112000 bps"                                                
    - name: test downloaded files
      shell: bash
      run: |
        echo '---->md5sum "Rexlambo Stay With Me.m4a"'    
        md5sum "Rexlambo Stay With Me.m4a"
        echo '---->md5sum "Rexlambo Stay With Me_1.m4a"' 
        md5sum "Rexlambo Stay With Me_1.m4a"
        echo '---->md5sum should be differentes because from differents urls' 
        test "$(md5sum 'Rexlambo Stay With Me.m4a' | cut -d " " -f 1)" == "$(md5sum 'Rexlambo Stay With Me_1.m4a' | cut -d " " -f 1)"     
    - name: test batch
      shell: bash
      run: |
        echo "launch batch and verify three downloads"
        ytdlmusic --auto --batch "./test/test.csv" "True" ";" 2 1 | grep "is ready" | wc -l | grep 3
        echo "test la presence des trois fichiers"
        test -f above_limujii.mp3
        test -f awake_nomyn.mp3
        test -f avalon_scandinavianz.mp3
    - name: test bad launch
      shell: bash
      run: |  
        echo "verifie le code erreur 2"        
        (ytdlmusic --tetet || echo $?) | grep "2"   
    - name: test short params
      shell: bash
      run: |
        echo "test une combinaison de flags courts"          
        ytdlmusic -fyd "Rexlambo" "Stay With Me"
        echo "test l existence du fichier généré"
        test -f rexlambo_stay_with_me_3.m4a  
    - name: test bad launch short params
      shell: bash
      run: |
        echo "verifie le code erreur 2 "            
        (ytdlmusic -dvUz || echo $?) | grep "2"     
    - name: test missing dependency error
      shell: bash
      run: | 
        echo "retire une dependance"         
        pip uninstall --yes youtube-dl
        echo "verifie la version" 
        ytdlmusic --version | grep "youtube-dl version            : NOT INSTALLED"
        echo "verifie que l erreur est remontee" 
        (ytdlmusic --auto "Rexlambo" "Stay With Me" || echo "good exit code") | grep "good exit code"
        echo "verifie que l erreur est propre" 
        (ytdlmusic --auto "Rexlambo" "Stay With Me" || echo "good exit code") | grep "Try to upgrade with 'ytdlmusic --update'"
    - name: test repair full-update
      shell: bash
      run: |  
        echo "verifie l upgrade"               
        printf 'y\n' | ytdlmusic --fullupdate | grep "Successfully installed youtube-dl"
        echo "verifie que l application refonctionne en HQ"
        ytdlmusic -dkQ --auto "Rexlambo" "Stay With Me"
        echo "verifie le quiet est fonctionnel"
        ytdlmusic --auto -q "Rexlambo" "Stay With Me" | grep "ffmpeg" || echo "ffmpeg non trouve" | grep "ffmpeg non trouve"
        echo "les md5 doivent etre differents (un en HQ l autre non)"
        md5sum rexlambo_stay_with_me_2.mp3
        md5sum rexlambo_stay_with_me_1.mp3
        test "$(md5sum rexlambo_stay_with_me_2.mp3 | cut -d " " -f 1)" != "$(md5sum rexlambo_stay_with_me_1.mp3 | cut -d " " -f 1)"        
        echo "verifie le telechargement keep"
        ytdlmusic -dkQ --auto "avalon" "scandinavianz"
        echo "verifie le nom genere"
        test -f avalon_scandinavianz_no_copyright_music_.mp3
        echo "verifie que l upgrade n esy plus disponible"
        printf 'y\n' | ytdlmusic --fullupdate | grep "Requirement already satisfied" | wc -l | grep 3
    - name: test bad launch (one parameter)
      shell: bash
      run: |   
        echo "ytdlmusic tetet renvoie un code erreur different de 0"       
        (ytdlmusic tetet || echo "good exit code") | grep "good exit code"
        echo "ytdlmusic tetet renvoie un Missing song"
        (ytdlmusic tetet || echo "good exit code") | grep "Missing song"  
        echo "ytdlmusic --n 13 renvoie un code erreur 2 (argparse)"
        (ytdlmusic -n 13 "Rexlambo" "Stay With Me" || echo $?) | grep "2"           