name: git

on:
  workflow_dispatch:

jobs:
  commit:
    name: push package on pypi
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: git version
        run: |
          git --version           
      - name: copy
        run: |
          cp .github/actions/full_test/action.yaml .github/actions/full_test_published/action.yaml
          cp .github/actions/minimal_test/action.yaml .github/actions/minimal_test_published/action.yaml    
      - name: commit push
        run: |
          git status
          git commit -am "CHORE : maj test to test_published"
          git push


