name: tag

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deduce relase
      run: echo ::set-output name=relase_tag::$(grep version setup.py | cut -d "\"" -f2)
    - name: Create a Release
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}      
      with:
        args: ${{ steps.vars.outputs.relase_tag }}



