name: test on push

on:
  push:

jobs:
  light_test:
    strategy:
      fail-fast: false
      matrix:
        os-version: ['ubuntu-18.04']
        python-version: [ '3.9' ]          
    runs-on: ${{ matrix.os-version }}
    name: test package on ${{ matrix.os-version }} with ${{ matrix.python-version }}
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: install ffmpeg with token
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: install md5sum for macos
        if: ${{ matrix.os-version == 'macos-latest' }} 
        run: |
          brew install md5sha1sum                    
      - name: update pip
        run: |
          python -m pip install --upgrade pip       
      - name: install ytdlmusic
        run: |
          pip install .
      - name: minimal test
        shell: bash
        run: |          
          printf '3\n' | ytdlmusic "Rexlambo" "Stay With Me"
          test -f rexlambo_stay_with_me.ogg
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64  
      - name: Launch test
        uses: ./.github/actions/full_test          