name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10-dev' ]
    name: test package with ${{ matrix.python-version }}
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64  
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      - name: install ytdlmusic
        run: |
          pip install .      
      - name: display version          
        run: |
          ytdlmusic --version
      - name: display help          
        run: |
          ytdlmusic --help  
      - name: display no_param          
        run: |
          ytdlmusic                   
      - name: test OGG auto          
        run: |
          ytdlmusic --auto "Rexlambo" "Stay With Me"
          test -f rexlambo_stay_with_me.ogg          
      - name: install ffmpeg
        run: |
          sudo apt-get -qq install ffmpeg          
      - name: test MP3 auto
        run: |          
          ytdlmusic --auto "Rexlambo" "Stay With Me"
          test -f rexlambo_stay_with_me.mp3 
      - name: test choice
        run: |          
          yes 3 | ytdlmusic "Rexlambo" "Stay With Me"
          test -f rexlambo_stay_with_me_1.mp3
      - name: test diff
        run: |          
          md5sum rexlambo_stay_with_me.mp3
          md5sum rexlambo_stay_with_me_1.mp3
          echo "les md5 doivent etre differents"
          test "$(md5sum rexlambo_stay_with_me.mp3)" != "$(md5sum rexlambo_stay_with_me_1.mp3)"
      - name: test bad param and correct exit code
        run: |          
          ytdlmusic --rttrt; if [[ $? -eq 0 ]]; then echo "exit code 0"; exit 1; else echo "exit code 1"; fi
          ytdlmusic --rttrt | grep "Bad parameters"
      - name: test missing dependency error
        run: |          
          pip3 uninstall youtube-dl
          ytdlmusic --version | grep "youtube-dl version            : NOT INSTALLED"
          ytdlmusic --auto "Rexlambo" "Stay With Me"; if [[ $? -eq 0 ]]; then echo "exit code 0"; exit 1; else echo "exit code 1"; fi
          ytdlmusic --auto "Rexlambo" "Stay With Me" | grep "Try to upgrade with 'ytdlmusic update'"
      - name: test full-update
        run: |               
          yes y | ytdlmusic --full-update
          ytdlmusic --auto "Rexlambo" "Stay With Me"
      - name: test update
        run: |               
          yes y | ytdlmusic update
          ytdlmusic --auto "Rexlambo" "Stay With Me"
