name: test ubuntu2004 python39

on:
  workflow_dispatch:

jobs:
  light_test:
    strategy:
      fail-fast: false
      matrix:
        os-version: ['ubuntu-20.04']
        python-version: [ '3.9' ]          
    runs-on: ${{ matrix.os-version }}
    name: test package on ${{ matrix.os-version }} with ${{ matrix.python-version }}
    steps:
      #preparation
      - name: Prepa test
        uses: ./.github/actions/prepa_install
      - name: install md5sum for macos
        if: ${{ matrix.os-version == 'macos-latest' }} 
        run: |
          brew install md5sha1sum                    
      #installation          
      - name: install ytdlmusic
        run: |
          pip install .
      #test 1
      - name: Launch minimal test
        uses: ./.github/actions/minimal_test 
      #configuration
      - name: install ffmpeg with token
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      #test 2    
      - name: Launch full test
        uses: ./.github/actions/full_test
    