name: test

on:
  workflow_dispatch:

jobs:
  full_test_ubuntu:
    strategy:
      matrix:
        python-version: [ '3.6' ]
        os-version: ['ubuntu-18.04','windows-latest','macos-latest']
        include:
          #keep only 3.9 python version for macos and windows
          - os-version: 'ubuntu-18.04'
            python-version: '3.7'
    runs-on: ${{ matrix.os-version }}
    name: test package on ${{ matrix.os-version }} with ${{ matrix.python-version }}
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64  
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      - name: install ytdlmusic
        run: |
          pip install .   
      - name: test 'ytdlmusic'         
        run: |
          ytdlmusic
          ytdlmusic | grep "SYNOPSIS"
          ytdlmusic | grep "ytdlmusic version             :"                   
      - name: test 'ytdlmusic --version'
        run: |
          ytdlmusic --version
          ytdlmusic --version | grep "ytdlmusic version             :"
      - name: test 'ytdlmusic --help'
        run: |
          ytdlmusic --help
          ytdlmusic --help | grep "SYNOPSIS"  
      - name: test 'ytdlmusic --auto artist title' without ffmpeg
        run: |
          ytdlmusic --auto "Rexlambo" "Stay With Me"
          test -f rexlambo_stay_with_me.ogg          
      - name: install ffmpeg
        if: ${{ matrix.os-version == 'ubuntu-18.04' }} 
        run: |
          sudo apt-get -qq install ffmpeg          
      - name: test 'ytdlmusic --auto artist title' with ffmpeg
        if: ${{ matrix.os-version == 'ubuntu-18.04' }} 
        run: |          
          ytdlmusic --auto "Rexlambo" "Stay With Me"
          test -f rexlambo_stay_with_me.mp3 
      - name: test 'ytdlmusic artist title' with ffmpegs
        if: ${{ matrix.os-version == 'ubuntu-18.04' }} 
        run: |          
          yes 3 | ytdlmusic "Rexlambo" "Stay With Me"
          test -f rexlambo_stay_with_me_1.mp3
      - name: test downloaded files
        if: ${{ matrix.os-version == 'ubuntu-18.04' }} 
        run: |          
          md5sum rexlambo_stay_with_me.mp3
          md5sum rexlambo_stay_with_me_1.mp3
          echo "les md5 doivent etre differents"
          test "$(md5sum rexlambo_stay_with_me.mp3)" != "$(md5sum rexlambo_stay_with_me_1.mp3)"
      - name: test bad launch
        run: |          
          (ytdlmusic --tetet || echo "good exit code") | grep "good exit code"
          ytdlmusic --rttrt | grep "Bad parameters"
      - name: test missing dependency error
        run: |          
          yes | pip3 uninstall youtube-dl
          ytdlmusic --version | grep "youtube-dl version            : NOT INSTALLED"
          (ytdlmusic --auto "Rexlambo" "Stay With Me" || echo "good exit code") | grep "good exit code"
          ytdlmusic --auto "Rexlambo" "Stay With Me" | grep "Try to upgrade with 'ytdlmusic update'"
      - name: test repair full-update
        run: |               
          yes y | ytdlmusic --full-update
          ytdlmusic --auto "Rexlambo" "Stay With Me"