name: test published package

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  full_test:
    strategy:
      fail-fast: false
      matrix:
        os-version: ['ubuntu-18.04','windows-latest','macos-latest']
        python-version: [ '3.9' ]
        include:
          - os-version: 'ubuntu-18.04'
            python-version: '3.6'
          - os-version: 'ubuntu-18.04'
            python-version: '3.7'
          - os-version: 'ubuntu-18.04'
            python-version: '3.8'
          - os-version: 'ubuntu-18.04'
            python-version: '3.10-dev'            
    runs-on: ${{ matrix.os-version }}
    name: test package on ${{ matrix.os-version }} with ${{ matrix.python-version }}
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64  
      - name: update pip
        run: |
          python -m pip install --upgrade pip       
      - name: install published ytdlmusic
        run: |
          pip install ytdlmusic   
      - name: test 'ytdlmusic'         
        run: |
          ytdlmusic
          ytdlmusic | grep "SYNOPSIS"
          ytdlmusic | grep "ytdlmusic version             :"                   
      - name: test 'ytdlmusic --version'
        run: |
          ytdlmusic --version
          ytdlmusic --version | grep "ytdlmusic version             :"
      - name: test 'ytdlmusic --help'
        run: |
          ytdlmusic --help
          ytdlmusic --help | grep "SYNOPSIS"  
      - name: test 'ytdlmusic --auto artist title'
        run: |
          ytdlmusic --auto "Rexlambo" "Stay With Me"
          test -f rexlambo_stay_with_me.ogg          
      - name: test 'ytdlmusic artist title' interactive mode
        run: |          
          printf '3\n' | ytdlmusic "Rexlambo" "Stay With Me"
          test -f rexlambo_stay_with_me_1.ogg
      - name: install ffmpeg with token
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: test 'ytdlmusic --auto artist title' with ffmpeg
        run: |          
          ytdlmusic --auto "Rexlambo" "Stay With Me"
          test -f rexlambo_stay_with_me.mp3 
      - name: install md5sum for macos
        if: ${{ matrix.os-version == 'macos-latest' }} 
        run: |
          brew install md5sha1sum                   
      - name: test downloaded files
        run: |          
          md5sum rexlambo_stay_with_me.ogg
          md5sum rexlambo_stay_with_me_1.ogg
          echo "les md5 doivent etre differents"
          test "$(md5sum rexlambo_stay_with_me.ogg)" != "$(md5sum rexlambo_stay_with_me_1.ogg)"
      - name: test 'ytdlmusic --auto artist title' with force ogg
        run: |          
          ytdlmusic --auto --ogg "Rexlambo" "Stay With Me"
          test -f rexlambo_stay_with_me_2.ogg       
      - name: test batch
        run: |
          echo "launch batch and verify three downloads"
          ytdlmusic --auto --batch="./test/test.csv"%True%";"%2%1 | grep "is ready" | wc -l | grep 3
          test -f above_limujii.mp3
          test -f awake_nomyn.mp3
          test -f avalon_scandinavianz.mp3
      - name: test bad launch
        run: |          
          (ytdlmusic --tetet || echo "good exit code") | grep "good exit code"
          ytdlmusic --rttrt | grep "Not recognized option"
      - name: test short params
        run: |          
          ytdlmusic -fyd "Rexlambo" "Stay With Me"
          test -f rexlambo_stay_with_me_3.ogg  
      - name: test bad launch short params
        run: |          
          (ytdlmusic -dvUz || echo "good exit code") | grep "good exit code"
          ytdlmusic -dvUz | grep "Not recognized option"      
      - name: test missing dependency error
        run: |          
          pip uninstall --yes youtube-dl
          ytdlmusic --version | grep "youtube-dl version            : NOT INSTALLED"
          (ytdlmusic --auto "Rexlambo" "Stay With Me" || echo "good exit code") | grep "good exit code"
          ytdlmusic --auto "Rexlambo" "Stay With Me" | grep "Try to upgrade with 'ytdlmusic update'"
      - name: test repair full-update
        run: |               
          printf 'y\n' | ytdlmusic --full-update
          ytdlmusic --auto "Rexlambo" "Stay With Me" 


